"""Generate original synthetic ZIPs; malformed variants are explicitly labeled.

Run from a source checkout: python fixtures/build_fixtures.py --output <new-directory>.
No archive is opened or extracted by this generator.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys

ROOT=Path(__file__).resolve().parents[1]
sys.path[:0]=[str(ROOT/'src'),str(ROOT)]
from archive_preflight.demo import eight_risks_zip,synthetic_zip
from tests.helpers_zip import make_zip,unicode_path
from tests.test_content import wire_zip,raw_deflate


def fixtures():
    regular=lambda name,**kw:dict(name=name,attr=0o100600<<16,**kw)
    encoding=[regular(b'caf\x82.txt'),regular('\u4e2d\u6587.txt'.encode('gb18030')),regular('\u30bd.txt'.encode('cp932')),
              regular('\u4e2d\u6587-utf8.txt'.encode(),flags=0x800),regular(b'valid.txt',extra=unicode_path(b'valid.txt','caf\u00e9.txt')),
              regular(b'invalid.txt',extra=unicode_path(b'invalid.txt','different.txt',crc=0))]
    tree=[regular(b'a'),regular(b'a/x'),regular(b'Dir/x'),regular(b'dir/y'),regular(b'dup'),regular(b'dup'),
          dict(name=b'empty/',data=b'',attr=0o40700<<16),dict(name=b'empty/',data=b'',attr=0o40700<<16)]
    paths=[b'C:relative',b'\\\\host\\share',b'/absolute',b'a\\b',b'a/../b',b'./x',b'a//b',b'nul\0x',b'escape\x1b[31m',b'line\nname','bidi\u202e.txt'.encode()]
    local=bytearray(wire_zip());local[30]=ord('b')
    flags=bytearray(wire_zip());struct.pack_into('<H',flags,6,0x800)
    overlaps=make_zip([regular(b'a'),regular(b'b',offset=0)])
    descriptor=bytearray(wire_zip(descriptor=True));position=descriptor.index(b'PK\x07\x08');descriptor[position+4]^=1
    missing64=bytearray(make_zip([b'x'],zip64=True));central=missing64.index(b'PK\x01\x02');struct.pack_into('<H',missing64,central+46+1,0xffff)
    return {
        'demo-eight-risks.zip':eight_risks_zip(),'encoding-mixed.zip':make_zip(encoding),
        'tree-collisions.zip':make_zip(tree),'nonstandard-paths.zip':make_zip([regular(n,flags=0x800 if b'\xe2' in n else 0) for n in paths]),
        'bounds-central-declaration.zip':make_zip([b'x'],cd_size=16*1024**2+1),
        'bounds-eocd-ambiguous.zip':make_zip([],comment=make_zip([])),
        'bounds-zip64-missing.zip':bytes(missing64),'bounds-depth.zip':make_zip([regular(b'/'.join([b'd']*65)+b'/x')]),
        'content-local-name.zip':bytes(local),'content-local-flags.zip':bytes(flags),'content-overlap.zip':overlaps,
        'content-bad-crc.zip':wire_zip(payload=raw_deflate(b'other')),
        'content-truncated.zip':wire_zip(payload=raw_deflate(b'hello')[:-1]),
        'content-low-declared.zip':wire_zip(b'A'*65536,declared=1),
        'content-tail-junk.zip':wire_zip(payload=raw_deflate(b'hello')+b'junk'),
        'content-descriptor.zip':bytes(descriptor),
        'safe-extract.zip':synthetic_zip([('stored.txt',b'original stored\n','file',0),('deflated.txt',b'original '*10000,'file',8),('empty',b'','file',0),('Dir/',b'','directory',0),('Dir/caf\u00e9.txt',b'original unicode\n','file',8)]),
        'report-injection.zip':make_zip([regular(n,flags=0x800) for n in [b'</script><img src=x onerror=alert(1)>',b'ESC\x1b[31m.txt',b'line\nname.txt','bidi\u202e.txt'.encode()]])}


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--output',type=Path,required=True);args=parser.parse_args()
    args.output.mkdir()
    manifest={}
    for name,blob in fixtures().items():
        (args.output/name).write_bytes(blob)
        manifest[name]={'bytes':len(blob),'sha256':hashlib.sha256(blob).hexdigest(),'synthetic':True}
    # Independent acceptance facts; no expected report generated by an engine.
    expected={'schemaVersion':1,'eightRiskCategories':['case','reserved','trailing','normalization','path-budget','traversal','symlink','declared-ratio'],
              'safeContent':{'stored.txt':'original stored\n','empty':'','Dir/caf\u00e9.txt':'original unicode\n'},
              'malformedContentMustFail':[n for n in manifest if n.startswith('content-')],
              'limitsAreRuntimeTests':['node-limit','mid-scan-source-change'],'files':manifest}
    (args.output/'expected.json').write_text(json.dumps(expected,ensure_ascii=True,indent=2)+'\n',encoding='ascii')
    print('Generated '+str(len(manifest))+' original synthetic ZIP fixtures.')


if __name__=='__main__':main()
